---
# Update the rev variable with the release version that you want, from the yamllint repo
# You can pass your custom .yamllint with args attribute.
repos:
  # https://yamllint.readthedocs.io/en/stable/
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint

  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
      - id: j2lint
        args: [--ignore, jinja-statements-indentation, jinja-variable-format, single-statement-per-line, jinja-variable-lower-case, --]
